Add mixpanel for logging stoprestarts
CFC-Servers/cfc_daily_restart pull request #13
Opened 2021-07-03 19:12 UTC by wrefgtzweve

2021-07-03 20:22 UTC, brandonsturgeon requested changes
Might be nice to include some data about how many people are on the server and how many in a row this was or something.

2021-07-03 20:22 UTC, brandonsturgeon commented on lua/ulx/modules/sh/cfc_stoprestart.lua
> +    mixpanelTrackPlyEvent( "Restart stopped", ply )
```suggestion
    mixpanelTrackPlyEvent( "Player stopped automatic restart", ply )
```

2021-07-03 21:46 UTC, wrefgtzweve commented
Good idea, will add

2021-07-12 05:32 UTC, brandonsturgeon commented
Syntax has changed a bit for Mixpanel - once that's updated we can merge

2021-08-17 21:13 UTC, wrefgtzweve commented
Ready for review

2021-08-17 21:15 UTC, brandonsturgeon approved these changes

2021-08-17 21:15 UTC, merged